---
- name: "2.2.1 | PATCH | Ensure ftp client is not installed"
  when:
    - not bozkarcis_ftp_client
    - bozkarcis_rule_2_2_1
  tags:
    - level1-server
    - automated
    - patch
    - ftp
    - NIST800-53R5_CM-7
    - rule_2.2.1
  ansible.builtin.package:
    name: ftp
    state: absent

- name: "2.2.2 | PATCH | Ensure ldap client is not installed"
  when:
    - not bozkarcis_openldap_clients_required
    - bozkarcis_rule_2_2_2
  tags:
    - level2-server
    - automated
    - patch
    - ldap
    - NIST800-53R5_CM-7
    - rule_2.2.2
  ansible.builtin.package:
    name: openldap-clients
    state: absent

- name: "2.2.3 | PATCH | Ensure telnet client is not installed"
  when:
    - not bozkarcis_telnet_required
    - bozkarcis_rule_2_2_3
  tags:
    - level1-server
    - automated
    - patch
    - telnet
    - NIST800-53R5_CM-7
    - rule_2.2.3
  ansible.builtin.package:
    name: telnet
    state: absent

- name: "2.2.4 | PATCH | Ensure tftp client is not installed"
  when:
    - not bozkarcis_tftp_client
    - bozkarcis_rule_2_2_4
  tags:
    - level1-server
    - automated
    - patch
    - tftp
    - NIST800-53R5_CM-7
    - rule_2.2.4
  ansible.builtin.package:
    name: tftp
    state: absent
