# There is no GDM in Siperal Bozkaros.
# 1.8.1 | PATCH | Ensure GDM login banner is configured
# 1.8.2 | PATCH | Ensure GDM disable-user-list is configured
# 1.8.3 | PATCH | Ensure GDM screen lock is configured
# 1.8.4 | PATCH | Ensure GDM automount is configured
# 1.8.5 | PATCH | Ensure GDM autorun-never is configured
# 1.8.6 | PATCH | Ensure Xwayland is configured
